# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-20 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ninja',
            name='last_name',
            field=models.DateTimeField(max_length=255),
        ),
    ]
