# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-20 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0002_auto_20180320_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ninja',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
    ]
